'use client';
import {ChangeEvent,useEffect,useMemo,useRef,useState} from 'react';
import {Area,AreaChart,Bar,BarChart,CartesianGrid,Cell,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {AlertCircle,BarChart3,BookOpen,CalendarRange,Camera,Check,CheckCircle2,ChevronRight,Cloud,CloudOff,Download,GripVertical,Home,ImagePlus,LayoutDashboard,LayoutGrid,Moon,Plus,RotateCcw,Search,Settings,ShieldCheck,Sparkles,Sun,Trash2,Upload,X} from 'lucide-react';
import {seedTrades} from '@/lib/sample';
import {Trade} from '@/lib/types';
import {deleteTrade as removeStoredTrade,loadTrades,replaceTrades,saveTrade} from '@/lib/storage';
import {CloudUser,deleteCloudTrade,getCloudUser,loadCloudTrades,loadStrategy,onAuthChange,saveStrategy,signIn,signOut,signUp,subscribeToTradeChanges,upsertCloudTrade} from '@/lib/cloud';

const money=(n:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(n);
type PageName='Dashboard'|'Journal'|'Analytics'|'Coach'|'Settings';
type RangePreset='7D'|'30D'|'90D'|'YTD'|'ALL'|'CUSTOM';
const desktopNav:[PageName,any][]=[['Dashboard',LayoutDashboard],['Journal',BookOpen],['Analytics',BarChart3],['Coach',Sparkles],['Settings',Settings]];
const today=()=>new Date().toISOString().slice(0,10);
const daysAgo=(n:number)=>{const d=new Date();d.setDate(d.getDate()-n);return d.toISOString().slice(0,10)};

export default function Page(){
 const [page,setPage]=useState<PageName>('Dashboard');
 const [dark,setDark]=useState(false);
 const [ready,setReady]=useState(false);
 const [trades,setTrades]=useState<Trade[]>([]);
 const [modal,setModal]=useState(false);
 const [selected,setSelected]=useState<Trade|null>(null);
 const [preset,setPreset]=useState<RangePreset>('30D');
 const [from,setFrom]=useState(daysAgo(29));
 const [to,setTo]=useState(today());
 const [toast,setToast]=useState('');
 const [user,setUser]=useState<CloudUser|null>(null);
 const [strategy,setStrategy]=useState('');
 const [syncState,setSyncState]=useState<'local'|'syncing'|'synced'|'error'>('local');
 useEffect(()=>{(async()=>{try{const savedTheme=localStorage.getItem('tradesea-theme');setDark(savedTheme?savedTheme==='dark':matchMedia('(prefers-color-scheme: dark)').matches);let stored=await loadTrades();const cloudUser=await getCloudUser();setUser(cloudUser);setStrategy(await loadStrategy());if(cloudUser){setSyncState('syncing');try{const cloud=await loadCloudTrades();const merged=[...cloud,...stored.filter(local=>!cloud.some(remote=>remote.id===local.id))].sort((a,b)=>b.date.localeCompare(a.date));stored=merged;await replaceTrades(merged);setSyncState('synced')}catch{setSyncState('error')}}if(!stored.length){stored=seedTrades;await replaceTrades(stored)}setTrades(stored);if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{})}finally{setReady(true)}})();const offAuth=onAuthChange(async cloudUser=>{setUser(cloudUser);if(cloudUser){setSyncState('syncing');try{const cloud=await loadCloudTrades();const local=await loadTrades();for(const trade of local.filter(t=>!cloud.some(c=>c.id===t.id)))await upsertCloudTrade(trade);const fresh=await loadCloudTrades();await replaceTrades(fresh);setTrades(fresh);setStrategy(await loadStrategy());setSyncState('synced')}catch{setSyncState('error')}}else setSyncState('local')});return offAuth},[]);
 useEffect(()=>{if(ready)localStorage.setItem('tradesea-theme',dark?'dark':'light')},[dark,ready]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2600);return()=>clearTimeout(t)},[toast]);
 const range=useMemo(()=>{if(preset==='ALL')return{from:'0000-01-01',to:'9999-12-31'};if(preset==='CUSTOM')return{from,to};if(preset==='YTD')return{from:`${new Date().getFullYear()}-01-01`,to:today()};const n=preset==='7D'?6:preset==='30D'?29:89;return{from:daysAgo(n),to:today()}},[preset,from,to]);
 useEffect(()=>{if(!user)return;const refresh=async()=>{try{const cloud=await loadCloudTrades();await replaceTrades(cloud);setTrades(cloud);setSyncState('synced')}catch{setSyncState('error')}};return subscribeToTradeChanges(refresh)},[user?.id]);
 const filtered=useMemo(()=>trades.filter(t=>t.date>=range.from&&t.date<=range.to),[trades,range]);
 const stats=useMemo(()=>calcStats(filtered),[filtered]);
 const add=async(trade:Trade)=>{await saveTrade(trade);setTrades(v=>[trade,...v]);setModal(false);setPage('Journal');setToast(user?'Trade saved — syncing to your devices':'Trade saved offline on this device');if(user){setSyncState('syncing');try{const synced=await upsertCloudTrade(trade);await saveTrade(synced);setTrades(v=>v.map(t=>t.id===synced.id?synced:t));setSyncState('synced')}catch{setSyncState('error')}}};
 const del=async(id:string)=>{const existing=trades.find(t=>t.id===id);await removeStoredTrade(id);setTrades(v=>v.filter(t=>t.id!==id));setSelected(null);setToast('Trade deleted');if(user)deleteCloudTrade(id,existing?.screenshotPath).catch(()=>setSyncState('error'))};
 if(!ready)return <div className="splash"><div className="brandmark">S</div><b>TradeSea</b></div>;
 return <div className={dark?'app dark':'app'}>
  <aside className="desktop-sidebar"><div className="brand"><span className="logo">S</span><b>TradeSea</b></div><button className="primary new-desktop" onClick={()=>setModal(true)}><Plus size={18}/>Journal trade</button><nav>{desktopNav.map(([name,Icon])=><button key={name} className={page===name?'active':''} onClick={()=>setPage(name)}><Icon size={19}/><span>{name}</span></button>)}</nav><div className="storage-note"><ShieldCheck/><div><b>Offline-safe</b><small>Saved to this device</small></div></div><div className="private-pill"><span>N</span><div><b>Nazzy</b><small>Private journal</small></div></div></aside>
  <main><header><div><p className="eyebrow">PRIVATE TRADING JOURNAL</p><h1>{page==='Dashboard'?'Good evening, Nazir':page}</h1><p>{page==='Dashboard'?'Your edge, made clear.':'Review your execution and improve.'}</p></div><div className="header-actions"><span className="offline-badge"><CloudOff/> {user?(syncState==='syncing'?'Syncing…':syncState==='error'?'Sync issue':'Cloud synced'):'Offline-ready'}</span><button aria-label="Toggle theme" className="icon theme" onClick={()=>setDark(!dark)}>{dark?<Sun size={20}/>:<Moon size={20}/>}</button></div></header>
   {page==='Dashboard'&&<Dashboard stats={stats} trades={filtered} open={setSelected} journal={()=>setModal(true)} preset={preset} setPreset={setPreset} from={from} to={to} setFrom={setFrom} setTo={setTo}/>} 
   {page==='Journal'&&<Journal trades={trades} open={setSelected} journal={()=>setModal(true)}/>} 
   {page==='Analytics'&&<Analytics trades={filtered} preset={preset} setPreset={setPreset}/>} 
   {page==='Coach'&&<Coach trades={filtered}/>} 
   {page==='Settings'&&<SettingsPage trades={trades} user={user} strategy={strategy} setStrategy={setStrategy} replace={async(t)=>{await replaceTrades(t);setTrades(t);setToast('Backup restored')}} notify={setToast}/>}
  </main>
  <nav className="mobile-tabs"><button className={page==='Dashboard'?'active':''} onClick={()=>setPage('Dashboard')}><Home/><span>Home</span></button><button className={page==='Journal'?'active':''} onClick={()=>setPage('Journal')}><BookOpen/><span>Journal</span></button><button className="journal-fab" onClick={()=>setModal(true)} aria-label="Journal a trade"><Plus/></button><button className={page==='Analytics'?'active':''} onClick={()=>setPage('Analytics')}><BarChart3/><span>Analytics</span></button><button className={page==='Coach'?'active':''} onClick={()=>setPage('Coach')}><Sparkles/><span>AI Coach</span></button></nav>
  {modal&&<TradeSheet close={()=>setModal(false)} add={add} strategy={strategy} recent={trades.slice(0,15)}/>} 
  {selected&&<Detail trade={selected} close={()=>setSelected(null)} remove={()=>del(selected.id)}/>} 
  {toast&&<div className="toast">{toast}</div>}
 </div>
}

function calcStats(trades:Trade[]){const pnl=trades.reduce((a,t)=>a+t.pnl,0),wins=trades.filter(t=>t.outcome==='Win').length,losses=trades.filter(t=>t.outcome==='Loss').length,be=trades.filter(t=>t.outcome==='BE').length,totalR=trades.reduce((a,t)=>a+t.rMultiple,0);return{pnl,wins,losses,be,win:wins/(trades.length||1)*100,avg:totalR/(trades.length||1),r:totalR,adherence:trades.filter(t=>t.followedPlan).length/(trades.length||1)*100,count:trades.length}}
function DateFilter({preset,setPreset,from,to,setFrom,setTo}:any){return <div className="date-filter"><div className="preset-row">{(['7D','30D','90D','YTD','ALL'] as RangePreset[]).map(p=><button key={p} className={preset===p?'active':''} onClick={()=>setPreset(p)}>{p}</button>)}<button className={preset==='CUSTOM'?'active':''} onClick={()=>setPreset('CUSTOM')}><CalendarRange/>Custom</button></div>{preset==='CUSTOM'&&<div className="custom-range"><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><span>to</span><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>}</div>}
type DashboardTileId='metrics'|'equity'|'winloss'|'direction'|'setups'|'recent'|'focus';
type TileSize='small'|'medium'|'wide';
type DashboardTile={id:DashboardTileId,size:TileSize};
const DEFAULT_TILES:DashboardTile[]=[
 {id:'metrics',size:'wide'},
 {id:'equity',size:'wide'},
 {id:'winloss',size:'small'},
 {id:'direction',size:'small'},
 {id:'recent',size:'medium'},
 {id:'focus',size:'medium'}
];
const TILE_META:Record<DashboardTileId,{label:string,description:string,defaultSize:TileSize}>={
 metrics:{label:'Key metrics',description:'Win rate, average R, plan adherence and trade count.',defaultSize:'wide'},
 equity:{label:'Performance curve',description:'Your cumulative P&L for the selected date range.',defaultSize:'wide'},
 winloss:{label:'Win / loss wheel',description:'A compact green and red outcome wheel.',defaultSize:'small'},
 direction:{label:'Long vs short',description:'A compact breakdown of your trade direction.',defaultSize:'small'},
 setups:{label:'Setup performance',description:'Your best setups ranked by average R.',defaultSize:'medium'},
 recent:{label:'Recent trades',description:'Quick access to your latest journal entries.',defaultSize:'medium'},
 focus:{label:'AI focus',description:'A focused coaching prompt based on your journal.',defaultSize:'medium'}
};
function normaliseTiles(raw:unknown):DashboardTile[]{
 if(!Array.isArray(raw))return DEFAULT_TILES;
 const validIds=Object.keys(TILE_META) as DashboardTileId[];
 const parsed=raw.map((item:any)=>typeof item==='string'?{id:item,size:TILE_META[item as DashboardTileId]?.defaultSize}:{id:item?.id,size:item?.size}).filter((item:any)=>validIds.includes(item.id)).map((item:any)=>({id:item.id as DashboardTileId,size:(['small','medium','wide'].includes(item.size)?item.size:TILE_META[item.id as DashboardTileId].defaultSize) as TileSize}));
 return parsed.length?parsed:DEFAULT_TILES;
}
function Dashboard({stats,trades,open,journal,preset,setPreset,from,to,setFrom,setTo}:any){
 const equity=useMemo(()=>{let v=0;return[...trades].reverse().map((t:Trade)=>({date:new Date(t.date).toLocaleDateString('en-GB',{day:'numeric',month:'short'}),value:v+=t.pnl}))},[trades]);
 const [tiles,setTiles]=useState<DashboardTile[]>(DEFAULT_TILES);
 const [customising,setCustomising]=useState(false);
 const [editMode,setEditMode]=useState(false);
 const [dragged,setDragged]=useState<DashboardTileId|null>(null);
 useEffect(()=>{try{const saved=localStorage.getItem('tradesea-dashboard-tiles-v2')||localStorage.getItem('tradesea-dashboard-tiles');if(saved)setTiles(normaliseTiles(JSON.parse(saved)))}catch{}},[]);
 useEffect(()=>{localStorage.setItem('tradesea-dashboard-tiles-v2',JSON.stringify(tiles))},[tiles]);
 const active=(id:DashboardTileId)=>tiles.some(t=>t.id===id);
 const toggle=(id:DashboardTileId)=>setTiles(v=>active(id)?v.filter(x=>x.id!==id):[...v,{id,size:TILE_META[id].defaultSize}]);
 const setSize=(id:DashboardTileId,size:TileSize)=>setTiles(v=>v.map(t=>t.id===id?{...t,size}:t));
 const reorder=(target:DashboardTileId)=>{if(!dragged||dragged===target)return;setTiles(v=>{const moving=v.find(x=>x.id===dragged);if(!moving)return v;const next=v.filter(x=>x.id!==dragged);const index=next.findIndex(x=>x.id===target);next.splice(index<0?next.length:index,0,moving);return next});setDragged(null)};
 const directions=[{name:'Long',value:trades.filter((t:Trade)=>t.direction==='Long').length},{name:'Short',value:trades.filter((t:Trade)=>t.direction==='Short').length}].filter(x=>x.value);
 const outcomes=[{name:'Wins',value:stats.wins},{name:'Losses',value:stats.losses},{name:'Break even',value:stats.be}].filter(x=>x.value);
 const setups=group(trades,'setup').slice(0,5);
 const renderTile=(tile:DashboardTile)=>{
  const {id,size}=tile;
  const shell=(content:any)=> <div key={id} className={`dashboard-tile-shell tile-size-${size} tile-kind-${id} ${editMode?'is-editing':''}`} draggable={editMode} onDragStart={()=>setDragged(id)} onDragEnd={()=>setDragged(null)} onDragOver={e=>{if(editMode)e.preventDefault()}} onDrop={()=>editMode&&reorder(id)}>{editMode&&<div className="tile-edit-bar"><span><GripVertical/>Drag to move</span><div className="tile-size-control">{(['small','medium','wide'] as TileSize[]).map(s=><button key={s} className={size===s?'active':''} onClick={()=>setSize(id,s)}>{s==='small'?'S':s==='medium'?'M':'L'}</button>)}</div></div>}{content}</div>;
  if(id==='metrics')return shell(<section className="metric-strip"><Metric label="Win rate" value={`${stats.win.toFixed(0)}%`}/><Metric label="Average R" value={`${stats.avg.toFixed(2)}R`}/><Metric label="Plan followed" value={`${stats.adherence.toFixed(0)}%`}/><Metric label="Total trades" value={`${stats.count}`}/></section>);
  if(id==='equity')return shell(<article className="card equity"><Title title="Performance" meta={preset==='CUSTOM'?`${from} – ${to}`:preset}/><div className="chart">{equity.length?<ResponsiveContainer><AreaChart data={equity} margin={{left:-20,right:4}}><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--accent)" stopOpacity=".28"/><stop offset="1" stopColor="var(--accent)" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--line)"/><XAxis dataKey="date" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip contentStyle={{borderRadius:14,border:'1px solid var(--line)',background:'var(--solid-panel)',color:'var(--text)'}}/><Area type="monotone" dataKey="value" stroke="var(--accent)" strokeWidth={3} fill="url(#area)"/></AreaChart></ResponsiveContainer>:<EmptyMini/>}</div></article>);
  if(id==='winloss')return shell(<article className="card donut-tile compact-donut"><Title title="Wins & losses" meta={`${stats.count} trades`}/><div className="donut-wrap">{outcomes.length?<><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={outcomes} dataKey="value" nameKey="name" innerRadius="61%" outerRadius="84%" paddingAngle={3} stroke="none">{outcomes.map((_:any,i:number)=><Cell key={i} fill={['#27c58b','#ff5c68','#a1a1aa'][i]}/>)}</Pie><Tooltip contentStyle={{borderRadius:14,border:'1px solid var(--line)',background:'var(--solid-panel)',color:'var(--text)'}}/></PieChart></ResponsiveContainer><div className="donut-centre"><strong>{stats.win.toFixed(0)}%</strong><span>win rate</span></div></>:<EmptyMini/>}</div><div className="legend-row"><span><i className="win-dot"/>{stats.wins} wins</span><span><i className="loss-dot"/>{stats.losses} losses</span>{stats.be>0&&<span><i className="be-dot"/>{stats.be} BE</span>}</div></article>);
  if(id==='direction')return shell(<article className="card donut-tile compact-donut"><Title title="Trade direction" meta="Long vs short"/><div className="donut-wrap">{directions.length?<><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={directions} dataKey="value" nameKey="name" innerRadius="61%" outerRadius="84%" paddingAngle={3} stroke="none">{directions.map((_:any,i:number)=><Cell key={i} fill={['#6657f5','#21b4a7'][i]}/>)}</Pie><Tooltip contentStyle={{borderRadius:14,border:'1px solid var(--line)',background:'var(--solid-panel)',color:'var(--text)'}}/></PieChart></ResponsiveContainer><div className="donut-centre"><strong>{stats.count}</strong><span>trades</span></div></>:<EmptyMini/>}</div><div className="legend-row">{directions.map((d:any,i:number)=><span key={d.name}><i style={{background:i?'#21b4a7':'#6657f5'}}/>{d.value} {d.name.toLowerCase()}</span>)}</div></article>);
  if(id==='setups')return shell(<article className="card"><Title title="Best setups" meta="Average R"/><div className="setup-list">{setups.length?setups.map((x:any)=><div key={x.name}><span>{x.name}</span><b className={x.r>=0?'positive':'negative'}>{x.r>=0?'+':''}{x.r.toFixed(2)}R</b></div>):<EmptyMini/>}</div></article>);
  if(id==='recent')return shell(<article className="card"><Title title="Recent trades" meta="Tap to review"/>{trades.length?<TradeCards trades={trades.slice(0,size==='wide'?4:2)} open={open}/>:<EmptyMini/>}</article>);
  return shell(<article className="card insight-card"><Sparkles/><div><span>AI focus</span><h3>{stats.adherence>=75?'Protect your best setups.':'Slow down before entry.'}</h3><p>{stats.count?`You followed your plan on ${stats.adherence.toFixed(0)}% of trades in this period. Keep journaling the reason behind every entry.`:'Choose a wider date range or add a new trade.'}</p></div></article>);
 };
 return <>
 <div className="dashboard-toolbar"><DateFilter {...{preset,setPreset,from,to,setFrom,setTo}}/><button className={editMode?'customise-button active':'customise-button'} onClick={()=>{setCustomising(true);setEditMode(true)}}><LayoutGrid/>{editMode?'Editing dashboard':'Customise dashboard'}</button></div>
 <section className="hero"><div><span>Net P&amp;L</span><strong className={stats.pnl>=0?'positive':'negative'}>{money(stats.pnl)}</strong><p>{stats.r>=0?'+':''}{stats.r.toFixed(1)}R across {stats.count} trades</p></div><button onClick={journal}><ImagePlus/>Journal trade</button></section>
 {editMode&&<div className="edit-dashboard-banner"><span><GripVertical/>Drag tiles to rearrange them. TradeSea automatically fits the grid around each tile.</span><button onClick={()=>setEditMode(false)}>Finish editing</button></div>}
 <section className="dashboard-widget-grid">{tiles.map(renderTile)}</section>
 {customising&&<div className="sheet-backdrop customise-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget){setCustomising(false);setEditMode(false)}}}><section className="widget-picker redesigned"><div className="sheet-head"><div><p className="eyebrow">CUSTOMISE TRADESEA</p><h2>Build your dashboard</h2><p>Choose your tiles, set their size, then drag them into place directly on the dashboard.</p></div><button className="icon" onClick={()=>{setCustomising(false);setEditMode(false)}}><X/></button></div><div className="widget-gallery">{(Object.keys(TILE_META) as DashboardTileId[]).map(id=>{const enabled=active(id);const tile=tiles.find(t=>t.id===id);return <article key={id} className={enabled?'widget-choice selected':'widget-choice'}><button className="widget-choice-main" onClick={()=>toggle(id)}><span className={`widget-preview preview-${id}`}>{id==='winloss'||id==='direction'?<span className="mini-ring"/>:id==='equity'?<span className="mini-line"/>:id==='metrics'?<><i/><i/><i/></>:<LayoutGrid/>}</span><span className="widget-copy"><b>{TILE_META[id].label}</b><small>{TILE_META[id].description}</small></span><span className="widget-check">{enabled?<Check/>:<Plus/>}</span></button>{enabled&&<div className="choice-size"><span>Tile size</span><div>{(['small','medium','wide'] as TileSize[]).map(s=><button key={s} className={tile?.size===s?'active':''} onClick={()=>setSize(id,s)}>{s==='small'?'Small':s==='medium'?'Medium':'Wide'}</button>)}</div></div>}</article>})}</div><div className="widget-actions"><button className="secondary" onClick={()=>setTiles(DEFAULT_TILES)}><RotateCcw/>Reset layout</button><button className="primary" onClick={()=>setCustomising(false)}>Arrange tiles</button></div></section></div>}
 </>}
function Metric({label,value}:{label:string,value:string}){return <div><span>{label}</span><b>{value}</b></div>}
function Title({title,meta}:{title:string,meta:string}){return <div className="card-title"><h2>{title}</h2><span>{meta}</span></div>}
function EmptyMini(){return <div className="empty-mini"><span>No trades in this period</span></div>}

function Journal({trades,open,journal}:{trades:Trade[],open:(t:Trade)=>void,journal:()=>void}){const[q,setQ]=useState('');const filtered=trades.filter(t=>(t.instrument+t.setup+t.session+t.emotion).toLowerCase().includes(q.toLowerCase()));return <section className="journal-page"><div className="journal-actions"><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search instrument, setup or emotion"/></div><button className="primary" onClick={journal}><Plus/>Add trade</button></div>{filtered.length?<TradeCards trades={filtered} open={open} full/>:<div className="empty"><ImagePlus/><h2>No trades found</h2><p>Upload a screenshot to create your first entry.</p><button className="primary" onClick={journal}>Journal a trade</button></div>}</section>}
function TradeCards({trades,open,full=false}:{trades:Trade[],open:(t:Trade)=>void,full?:boolean}){return <div className={full?'trade-cards full':'trade-cards'}>{trades.map(t=><button className="trade-card" key={t.id} onClick={()=>open(t)}>{t.screenshot?<img src={t.screenshot} alt="Trade chart"/>:<div className="chart-placeholder"><BarChart3/></div>}<div className="trade-copy"><div><span>{new Date(t.date).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})} · {t.session}</span><h3>{t.instrument} <small className={t.direction==='Long'?'positive':'negative'}>{t.direction}</small></h3></div><div className="trade-result"><b className={t.pnl>=0?'positive':'negative'}>{t.rMultiple>0?'+':''}{t.rMultiple.toFixed(2)}R</b><small>{money(t.pnl)}</small></div><div className="tags"><span>{t.setup}</span><span>{t.emotion}</span></div></div><ChevronRight className="chevron"/></button>)}</div>}

function Analytics({trades,preset,setPreset}:{trades:Trade[],preset:RangePreset,setPreset:(p:RangePreset)=>void}){const setups=group(trades,'setup'),sessions=group(trades,'session');const directions=[{name:'Bullish',value:trades.filter(t=>t.direction==='Long').length},{name:'Bearish',value:trades.filter(t=>t.direction==='Short').length}];return <section><div className="compact-presets">{(['7D','30D','90D','YTD','ALL'] as RangePreset[]).map(p=><button key={p} className={preset===p?'active':''} onClick={()=>setPreset(p)}>{p}</button>)}</div><div className="analytics-page"><article className="card analytics-card"><Title title="Direction" meta={`${trades.length} trades`}/><div className="donut"><ResponsiveContainer><PieChart><Pie data={directions} dataKey="value" innerRadius={62} outerRadius={84} paddingAngle={5}><Cell fill="var(--green)"/><Cell fill="var(--red)"/></Pie><Tooltip/></PieChart></ResponsiveContainer><strong>{trades.length}<small>trades</small></strong></div></article><article className="card analytics-card wide"><Title title="Average R by setup" meta="Your strongest edge"/><div className="chart analytics-chart">{setups.length?<ResponsiveContainer><BarChart data={setups} layout="vertical"><XAxis type="number" hide/><YAxis type="category" dataKey="name" width={145} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="r" fill="var(--accent)" radius={[0,9,9,0]}/></BarChart></ResponsiveContainer>:<EmptyMini/>}</div></article><article className="card analytics-card"><Title title="Sessions" meta="Average R"/><div className="stat-list">{sessions.map(s=><div key={s.name}><span>{s.name}<small>{s.count} trades</small></span><b className={s.r>=0?'positive':'negative'}>{s.r.toFixed(2)}R</b></div>)}</div></article></div></section>}
function Coach({trades}:{trades:Trade[]}){const best=group(trades,'setup')[0],broken=trades.filter(t=>!t.followedPlan),stats=calcStats(trades);return <section className="coach-page"><div className="coach-orb"><Sparkles/></div><p className="eyebrow">YOUR AI COACH</p><h2>{trades.length?'Your journal is revealing a pattern.':'Start journaling to unlock insights.'}</h2><p className="coach-lead">Every insight is generated from your selected period.</p><div className="coach-feed"><article><span>Strongest edge</span><h3>{best?.name||'Not enough data yet'}</h3><p>{best?`${best.count} recorded trades with an average result of ${best.r.toFixed(2)}R.`:'Add a few trades to discover your highest-performing setup.'}</p></article><article><span>Behaviour to watch</span><h3>{broken.length} plan break{broken.length===1?'':'s'}</h3><p>{broken.length?'Your rule-breaking trades are weakening otherwise good analysis.':'Excellent — every recorded trade followed your plan.'}</p></article><article><span>Consistency score</span><h3>{Math.round((stats.adherence+Math.min(stats.win,100))/2)}/100</h3><p>Built from your plan adherence and outcome consistency.</p></article></div></section>}

function TradeSheet({close,add,strategy,recent}:{close:()=>void,add:(t:Trade)=>void,strategy:string,recent:Trade[]}){const[file,setFile]=useState('');const[scanning,setScanning]=useState(false);const[error,setError]=useState('');const[ai,setAi]=useState<any>(null);const[f,setF]=useState({date:today(),instrument:'',direction:'Long',setup:'',session:'London',entry:'',stopLoss:'',takeProfit:'',exit:'',risk:'100',pnl:'',emotion:'Calm',followedPlan:true,notes:''});const input=useRef<HTMLInputElement>(null);
 const image=async(e:ChangeEvent<HTMLInputElement>)=>{const raw=e.target.files?.[0];if(!raw)return;setError('');setScanning(true);const compressed=await compressImage(raw);setFile(compressed);try{const summaries=recent.map(t=>({instrument:t.instrument,direction:t.direction,setup:t.setup,session:t.session,rMultiple:t.rMultiple,outcome:t.outcome,followedPlan:t.followedPlan,emotion:t.emotion,ai:t.ai}));const response=await fetch('/api/analyze-trade',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:compressed,strategy,recentTrades:summaries})});const data=await response.json();if(!response.ok)throw new Error(data.error||'AI analysis failed');setAi(data);setF(v=>({...v,instrument:data.instrument||v.instrument,direction:data.direction==='Short'?'Short':'Long',setup:data.setup||data.concepts?.join(' + ')||v.setup,session:data.session||v.session,entry:data.entry??v.entry,stopLoss:data.stopLoss??v.stopLoss,takeProfit:data.takeProfit??v.takeProfit,exit:data.exit??v.exit,followedPlan:data.followedPlan??v.followedPlan,notes:data.review||v.notes}))}catch(err:any){setError(`${err.message} You can still enter the trade manually.`)}finally{setScanning(false)}};
 const submit=()=>{const entry=+f.entry,sl=+f.stopLoss,tp=+f.takeProfit,exit=+f.exit,risk=+f.risk;if(!f.instrument||!entry||!sl||!exit){setError('Instrument, entry, stop and exit are required.');return}const riskDistance=Math.abs(entry-sl)||1;const achieved=f.direction==='Long'?(exit-entry)/riskDistance:(entry-exit)/riskDistance;const pnl=f.pnl!==''?+f.pnl:risk*achieved;add({id:crypto.randomUUID(),date:f.date,instrument:f.instrument.toUpperCase(),direction:f.direction as 'Long'|'Short',setup:f.setup||'Uncategorised',session:f.session,entry,stopLoss:sl,takeProfit:tp||entry,exit,risk,pnl:+pnl.toFixed(2),rMultiple:+achieved.toFixed(2),outcome:achieved>0.05?'Win':achieved<-.05?'Loss':'BE',emotion:f.emotion,followedPlan:f.followedPlan,notes:f.notes,screenshot:file,ai:ai?{confidence:ai.confidence,concepts:ai.concepts,mistake:ai.mistake,improvement:ai.improvement,review:ai.review}:undefined,updatedAt:new Date().toISOString()})};
 return <div className="sheet-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="trade-sheet"><div className="grabber"/><div className="sheet-head"><div><p className="eyebrow">NEW JOURNAL ENTRY</p><h2>Journal your trade</h2><p>Upload a screenshot and TradeSea will compare it with your strategy.</p></div><button className="icon" onClick={close}><X/></button></div><input ref={input} hidden type="file" accept="image/*" onChange={image}/><button className={file?'upload-zone preview':'upload-zone'} onClick={()=>input.current?.click()}>{file?<><img src={file} alt="Screenshot preview"/>{scanning&&<div className="scan-overlay"><div className="spinner"/>Reading chart and strategy…</div>}</>:<><div className="upload-icon"><Camera/></div><b>Choose screenshot</b><span>Photos, Camera, Files or desktop upload</span></>}</button>{file&&<button className="change-image" onClick={()=>input.current?.click()}><Upload/>Change image</button>}
 {ai&&<article className="ai-scan-card"><Sparkles/><div><div className="ai-scan-head"><b>TradeSea analysis</b><span>{Math.round((ai.confidence||0)*100)}% confidence</span></div><p>{ai.review}</p>{ai.mistake&&<div className="coach-points"><span><b>Mistake</b>{ai.mistake}</span><span><b>Improve</b>{ai.improvement}</span></div>}</div></article>}
 <div className="form-grid"><Field label="Date"><input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></Field><Field label="Instrument"><input value={f.instrument} onChange={e=>setF({...f,instrument:e.target.value})} placeholder="NAS100"/></Field><Field label="Direction"><select value={f.direction} onChange={e=>setF({...f,direction:e.target.value})}><option>Long</option><option>Short</option></select></Field><Field label="Entry"><input inputMode="decimal" value={f.entry} onChange={e=>setF({...f,entry:e.target.value})}/></Field><Field label="Stop loss"><input inputMode="decimal" value={f.stopLoss} onChange={e=>setF({...f,stopLoss:e.target.value})}/></Field><Field label="Take profit"><input inputMode="decimal" value={f.takeProfit} onChange={e=>setF({...f,takeProfit:e.target.value})}/></Field><Field label="Exit"><input inputMode="decimal" value={f.exit} onChange={e=>setF({...f,exit:e.target.value})}/></Field><Field label="Risk (£)"><input inputMode="decimal" value={f.risk} onChange={e=>setF({...f,risk:e.target.value})}/></Field><Field label="P&L (£) — optional"><input inputMode="decimal" value={f.pnl} onChange={e=>setF({...f,pnl:e.target.value})}/></Field><Field label="Setup"><input value={f.setup} onChange={e=>setF({...f,setup:e.target.value})}/></Field><Field label="Session"><select value={f.session} onChange={e=>setF({...f,session:e.target.value})}><option>London</option><option>New York</option><option>Asia</option><option>Other</option></select></Field><Field label="Emotion"><select value={f.emotion} onChange={e=>setF({...f,emotion:e.target.value})}><option>Calm</option><option>Confident</option><option>Focused</option><option>Hesitant</option><option>Frustrated</option><option>FOMO</option></select></Field><label className="switch-row"><span><b>Followed my plan</b><small>Did you respect your strategy and risk rules?</small></span><input type="checkbox" checked={f.followedPlan} onChange={e=>setF({...f,followedPlan:e.target.checked})}/></label><Field label="Notes" wide><textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})} placeholder="AI review and your own notes appear here."/></Field></div>{error&&<p className="form-error">{error}</p>}<div className="sticky-save"><button className="primary" onClick={submit}>Save and sync trade</button></div></section></div>}
function Field({label,children,wide=false}:{label:string,children:any,wide?:boolean}){return <label className={wide?'wide':''}>{label}{children}</label>}
function Detail({trade,close,remove}:{trade:Trade,close:()=>void,remove:()=>void}){const[confirming,setConfirming]=useState(false);return <div className="sheet-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="trade-sheet detail-sheet"><div className="sheet-head"><div><p className="eyebrow">TRADE REVIEW</p><h2>{trade.instrument} · {trade.direction}</h2><p>{new Date(trade.date).toLocaleDateString('en-GB',{dateStyle:'long'})}</p></div><button className="icon" onClick={close}><X/></button></div><div className="detail-image">{trade.screenshot?<img src={trade.screenshot} alt="Trade screenshot"/>:<BarChart3/>}</div><div className="detail-result"><strong className={trade.rMultiple>=0?'positive':'negative'}>{trade.rMultiple>0?'+':''}{trade.rMultiple.toFixed(2)}R</strong><span>{money(trade.pnl)}</span></div><div className="detail-stats"><Info label="Setup" value={trade.setup}/><Info label="Session" value={trade.session}/><Info label="Emotion" value={trade.emotion}/><Info label="Plan" value={trade.followedPlan?'Followed':'Broken'}/><Info label="Entry" value={String(trade.entry)}/><Info label="Exit" value={String(trade.exit)}/></div><div className="ai-review"><Sparkles/><div><b>TradeSea coach</b><p>{trade.ai?.review||trade.notes||'No AI review was recorded for this trade.'}</p>{trade.ai?.mistake&&<div className="coach-points"><span><b>Main mistake</b>{trade.ai.mistake}</span><span><b>Next improvement</b>{trade.ai.improvement}</span></div>}</div></div><div className="danger-zone">{confirming?<><p>Delete this trade permanently from every synced device?</p><div><button onClick={()=>setConfirming(false)}>Cancel</button><button className="danger" onClick={remove}>Yes, delete</button></div></>:<button className="delete-button" onClick={()=>setConfirming(true)}><Trash2/>Delete trade</button>}</div></section></div>}
function Info({label,value}:{label:string,value:string}){return <div><span>{label}</span><b>{value}</b></div>}
function SettingsPage({trades,replace,user,strategy,setStrategy,notify}:{trades:Trade[],replace:(t:Trade[])=>void,user:CloudUser|null,strategy:string,setStrategy:(v:string)=>void,notify:(v:string)=>void}){
 const file=useRef<HTMLInputElement>(null);
 const[email,setEmail]=useState('');
 const[password,setPassword]=useState('');
 const[authMode,setAuthMode]=useState<'signin'|'signup'>('signup');
 const[showPassword,setShowPassword]=useState(false);
 const[authError,setAuthError]=useState('');
 const[authStatus,setAuthStatus]=useState('');
 const[authLoading,setAuthLoading]=useState(false);
 const[saving,setSaving]=useState(false);
 const exportData=()=>{const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),strategy,trades},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`tradesea-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href)};
 const restore=async(e:ChangeEvent<HTMLInputElement>)=>{const raw=e.target.files?.[0];if(!raw)return;const parsed=JSON.parse(await raw.text());if(Array.isArray(parsed.trades))replace(parsed.trades);if(typeof parsed.strategy==='string'){setStrategy(parsed.strategy);await saveStrategy(parsed.strategy)}};
 const auth=async()=>{
  setAuthError('');setAuthStatus('');
  if(!email.trim()){setAuthError('Enter your email address.');return}
  if(password.length<6){setAuthError('Your password must contain at least 6 characters.');return}
  setAuthLoading(true);
  try{
   const result=authMode==='signin'?await signIn(email,password):await signUp(email,password);
   setAuthStatus(result.message);
   notify(result.message);
   if(result.signedIn){setPassword('')}
  }catch(err:any){setAuthError(err?.message||'Authentication failed. Please try again.')}
  finally{setAuthLoading(false)}
 };
 const saveRules=async()=>{setSaving(true);try{await saveStrategy(strategy);notify(user?'Strategy saved to your account':'Strategy saved locally — sign in to sync it')}finally{setSaving(false)}};
 return <section className="settings-page">
  <article className="card settings-hero"><ShieldCheck/><div><h2>{user?'Your journal is cloud synced.':'Connect your private cloud.'}</h2><p>{user?`Signed in as ${user.email}. Trades, screenshots and your strategy now follow you between desktop and iPhone.`:'Create one private TradeSea account, then sign into the same account on both devices.'}</p></div>{user&&<button className="secondary" onClick={()=>signOut()}>Sign out</button>}</article>
  {!user&&<article className="card auth-card auth-card-v2">
   <div className="auth-intro"><p className="eyebrow">PRIVATE TRADESEA ACCOUNT</p><h3>{authMode==='signup'?'Create your cloud account':'Welcome back'}</h3><p>{authMode==='signup'?'Your trades will sync securely between your desktop and iPhone.':'Sign in with the account you created on TradeSea.'}</p><div className="auth-benefits"><span><ShieldCheck/>Private to you</span><span><Cloud/>Cross-device sync</span></div></div>
   <div className="auth-panel">
    <div className="auth-tabs"><button className={authMode==='signup'?'active':''} onClick={()=>{setAuthMode('signup');setAuthError('');setAuthStatus('')}}>Create account</button><button className={authMode==='signin'?'active':''} onClick={()=>{setAuthMode('signin');setAuthError('');setAuthStatus('')}}>Sign in</button></div>
    <label>Email address<input autoComplete="email" type="email" inputMode="email" placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)} onKeyDown={e=>e.key==='Enter'&&auth()}/></label>
    <label>Password<div className="password-field"><input autoComplete={authMode==='signup'?'new-password':'current-password'} type={showPassword?'text':'password'} placeholder="At least 6 characters" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==='Enter'&&auth()}/><button type="button" onClick={()=>setShowPassword(v=>!v)}>{showPassword?'Hide':'Show'}</button></div></label>
    <button className="primary auth-submit" onClick={auth} disabled={authLoading}>{authLoading?'Please wait…':authMode==='signup'?'Create my account':'Sign in'}</button>
    {authStatus&&<div className="auth-message success"><CheckCircle2/><span>{authStatus}</span></div>}
    {authError&&<div className="auth-message error"><AlertCircle/><span>{authError}</span></div>}
    <p className="auth-help">{authMode==='signup'?'Supabase may send you a confirmation email. Check your junk folder too.':'Use the exact email and password from account creation.'}</p>
   </div>
  </article>}
  <article className="card strategy-card"><div><p className="eyebrow">MY TRADING STRATEGY</p><h3>Teach TradeSea how you trade</h3><p>Write your entry model, confirmations, invalidations, session rules, risk limits and reasons not to trade. The AI will compare every uploaded trade against these rules.</p></div><textarea value={strategy} onChange={e=>setStrategy(e.target.value)} placeholder={'Example:\nI trade NAS100 during London and New York.\nLong: sweep sell-side liquidity, bullish displacement, then entry in FVG in discount.\nStop below the sweep. Minimum 2R.\nNo entry before CHOCH. Maximum two losses per day.\nDo not trade while frustrated or after missing the original entry.'}/><div className="strategy-footer"><span>{strategy.length} characters</span><button className="primary" onClick={saveRules} disabled={saving}>{saving?'Saving…':'Save my strategy'}</button></div></article>
  <div className="settings-grid"><article className="card"><Download/><h3>Export backup</h3><p>Download your trades, AI reviews and strategy.</p><button className="primary" onClick={exportData}>Export {trades.length} trades</button></article><article className="card"><Upload/><h3>Restore backup</h3><p>Import a previous TradeSea backup.</p><input hidden ref={file} type="file" accept="application/json" onChange={restore}/><button className="secondary" onClick={()=>file.current?.click()}>Choose backup</button></article></div>
 </section>
}
function group(trades:Trade[],key:'setup'|'session'){const m=new Map<string,{name:string,count:number,r:number}>();trades.forEach(t=>{const name=t[key];const prev=m.get(name)||{name,count:0,r:0};prev.count++;prev.r+=t.rMultiple;m.set(name,prev)});return [...m.values()].map(x=>({...x,r:x.r/x.count})).sort((a,b)=>b.r-a.r)}
async function compressImage(file:File){return new Promise<string>((resolve,reject)=>{const img=new Image();img.onload=()=>{const max=1600,scale=Math.min(1,max/img.width,max/img.height);const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d')!.drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.78))};img.onerror=reject;img.src=URL.createObjectURL(file)})}
